---
 - name: Installatons of serves using roles
   hosts: dev
   become: true
   
   pre_tasks:
     - name: to update cache
       apt:
         update_cache: yes
   roles: 
     - Amyy16.wtf_nginx_role

 - name: Installation of apache on redhat os
   hosts: prod
   become: true

   pre_tasks:
     - name: To install firewalld and python3
       yum:
         name:
           - firewalld
           - python3-firewall
     - name: start firewalld and python3 firwall
       service:
         name: firewalld
         state: started
         enabled: true

   roles:
     - prateek8294.apache 
